### ISSUE TITLE
monster list window resize

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#332]
it's how I play regularly:
https://cdn.discordapp.com/attachments/699917093717671946/826485156612538428/0.jpg

so to show directions (distance and NSWE) for monsters player need to have enormous width:
https://cdn.discordapp.com/attachments/699917093717671946/826485167001698334/1.png

I've changed my font to 12x18, but it still doesn't help. Monster window atm ! 650 px ! size.

Suggestions:
1) reduce monster names in monster list to 10-20 characters... Atm it could be up to 40.
2) remove brackets from [U].. and align U to 'number' row
3) move number row closer to glyph row

with 10 chars per name - this will reduce size of this window from 650 to 250 px... 2.5 times
https://media.discordapp.net/attachments/699917093717671946/827818417150361640/Untitled-1.jpg?width=798&height=573

considering 'eating' asleep state - not sure should player know - is monster asleep or not in this window... knowing it name game less challenging.. so it's not very critical thing.

**Comment by igroglaz** [comment]
Even better solution: move coordinates to the beginning of the stroke, but color them so it will be easier to read, eg:
https://cdn.discordapp.com/attachments/699917093717671946/827822052072882187/Untitled-1.jpg

1) do not show '1' if there is only one monster. number of monsters should be written only if there are 2+ of them
2) color coordanate numbers to white color
3) color coordinate directions to green
4) remove spaces between numbers and directions
5) put everything closer

this way we wouldn't need to cut number of symbols in monster names :D

**Comment by draconisPW** [comment]
Location in V actually follows the window resizing. This is then a bug in current PWMAng code.

**Comment by draconisPW** [comment]
For example:
- t 1 mean-looking mercenary (asleep) ........... 14S 7W (big size)
- t 1 mean-looking mercenary (asleep) 14S 7W (medium size)
- t 1 mean-looki (asleep) 14S 7W (small size)

**Comment by draconisPW** [comment]
The problem is that V uses the size of the term when displaying monster list. MAng code doesn't use that at all and just uses a fixed value (75x22).

**Comment by draconisPW** [comment]
Fixed by sending the horizontal size of the subwindow when resizing monster list subwindow and using that value to generate the info. This fix added a new packet and will require a new version of the client.

**Comment by igroglaz** [comment]
problem still exist. it worked once when I replaced it, but then it again resetted to huuuge width (see my past stream  https://www.youtube.com/watch?v=LA6WUHe-FzU )

**Comment by igroglaz** [comment]
yep. you could set it up properly when you see monsters nearby. but then when you restart client - it become ultra wide again

**Comment by draconisPW** [comment]
Packet is only sent on resize. I'll also send a packet on initialize.

**Comment by draconisPW** [comment]
In fact I removed the packet sent on resize (which is called in each client) and instead I send it on each subwindow update (which is called in the common code). Much cleaner this way.
