### ISSUE TITLE
[bcc32 Error] z-file.c(533): E2140 Declaration is not allowed here

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#407]
![image](https://user-images.githubusercontent.com/39904162/125442579-9361282e-805d-4501-bbfd-83bdc460518e.png)

**Comment by draconisPW** [comment]
Yeah this is already fixed.

**Comment by igroglaz** [comment]
but this problem is still there.. can't compile server with latest build

**Comment by draconisPW** [comment]
You will have to wait for next commit.

**Comment by igroglaz** [comment]
oook, I'll rollback T then until it will be fixed ;)

**Comment by draconisPW** [comment]
Or you can just move the line 533 at the beginning of the function...
