### ISSUE TITLE
Server Lag issue on character creation which leads to timeout

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#412]
Darkfold kindly recorded this video:
https://youtu.be/nGcKzsMODF4

**Comment by draconisPW** [comment]
The "Setup.ready" change should have fixed this...

I'll try to debug by connecting to T server because I cannot reproduce this locally.

**Comment by draconisPW** [comment]
2:23 is impossible, you would have to press "a" to select a character in the list
2:38 is completely incomprehensible
Clearly this is not a correct state of event, so it's either in T client or shouldn't ever occur.

**Comment by draconisPW** [comment]
Closing this as a client compilation problem.

**Comment by igroglaz** [comment]
I didn't change anything like this in T client. You can see it in my fork https://github.com/igroglaz/Tangaria

**Comment by draconisPW** [comment]
Well yeah but this doesn't happen with PWMAng client, vid was not made with official PWMAng release, so I can't do anything.

**Comment by igroglaz** [comment]
I'm pretty sure the same thing will happen with PWMA too. It depends on player's ping. If player connect from USA - this thing could happen

**Comment by igroglaz** [comment]
so.. it's not "client compilation problem". it's both T and PWMA problem :)

**Comment by draconisPW** [comment]
Reopening. This has to do with SPACE beign pressed, not ENTER. Plus ENTER is not properly coded.

**Comment by draconisPW** [comment]
> if (!key && done)
    {
        if (Setup.ready)
		{
			if (first_escape) Send_clear();
			first_escape = false;
		}
        return;
    }

    /* Use command menus */
    if (key == KC_ENTER)
	{
		if (OPT(player, disable_enter) || !Setup.ready) return;
        cmd = textui_action_menu_choose();
	}

**Comment by draconisPW** [comment]
Fixed.

**Comment by igroglaz** [comment]
Problem is still there :(

I still see plenty of people who fail to enter the game, eg:

![Untitled-1](https://user-images.githubusercontent.com/39904162/132088464-5ef0bde6-3835-4abf-b833-f95fe0e46bed.jpg)

 My demo:
https://youtu.be/teWOWtvi44M
log from demo:
![2](https://user-images.githubusercontent.com/39904162/132088756-8e4b9123-c9db-4c13-a4a1-bece1a961528.jpg)

**Comment by draconisPW** [comment]
Yeah as predicted, I only tested Setup.ready vs ENTER and didn't test vs SPACE. I've added the check and now this should be really fixed.

**Comment by igroglaz** [comment]
I didn't change space behaviour. I'm pretty sure it's PWMA problem too, but to trigger it you need to connect not to your local server (which has 0 latency), but to distant server. Also maybe some other factors could affect it - like amount of account/characters.

I'll try to debug it locally and report

**Comment by draconisPW** [comment]
Can't happen for me, I've removed the "play" code so the client never connects to the server after pressing choice of character and this never triggers any packet. Same when connecting to T server, no packet is ever sent. The space key is intercepted and discarded, so if you press space and trigger an "unknown packet", then it's not from PWMA code.

**Comment by igroglaz** [comment]
Culprit is `Tangar.prf` (or any other .prf in \lib\user) file. When I moved it to debugging client - this problem starts to appear...

When I compare `Tangar.prf` with \lib\customize\`pref.prf`:

![image](https://user-images.githubusercontent.com/39904162/132187281-f5a34605-6a00-4bc8-9112-e2491f8537bc.png)

and

![image](https://user-images.githubusercontent.com/39904162/132187324-43687db5-c0d3-45ce-8440-59371a737917.png)

**Comment by igroglaz** [comment]
Also donno how to debug it.. as it doesnt crush. Btw where is debug point in client? In server it's `exit_game_panic`, but in client I didn't find it

**Comment by draconisPW** [comment]
Yeah it's not easy to debug this part, as the error appears on the server when receiving a packet it doesn't understand. The best is to put a breakpoint into the packet sending function.

**Comment by igroglaz** [comment]
finally found problem with timeouts (by testing all pieces of .prf file till found culprit).

I use [Space] ([space bar](https://en.wikipedia.org/wiki/Space_bar)) to 'L' around. For this I have this keymap:

```
keymap-act:[Escape]L
keymap-input:0: 
```

after :0: there is actually space... empty _

this keymap works alright in-game. BUT when I login to the game - it seems game trying to use this command while game isn't loaded 🤣 

I've tried to replace it with

```
keymap-act:[Escape]L
keymap-input:0:[SPACE]
```

but then it doesn't work in-game.. so we need to do something with this

===============

ALSO. It doesn't solve the mystery with other players. New players can't connect to the game, BUT they don't have _ space keymapped anywhere! They use blank client.... "The best is to put a breakpoint into the packet sending function" - please could you point where exactly to put such breakpoint 🙏

**Comment by draconisPW** [comment]
Packet_printf() in sockbuf.c is a good starting point.

For other players, a good guess is that they use an outdated client which doesn't have the same packet list so the packets are shifted from client to server and the data sent is not equal to the data received. I'm going to release final 1.5 at the end of the week, this should remove that possibility (players will have to update to 1.5 nonbeta client to play on 1.5 nonbeta server).

**Comment by igroglaz** [comment]
Cool :) What about [Space] problem?
